#!/bin/bash
set -e

# Creates non-super-user to access database with RLS restrictions
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $DB_USERNAME;
    GRANT USAGE ON SCHEMA public TO $DB_USERNAME;
    GRANT CREATE ON SCHEMA public TO $DB_USERNAME;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DB_USERNAME;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $DB_USERNAME;
EOSQL